import type { Metadata } from "next";
import { Inter, Lusitana, Source_Serif_4 } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});
const sourceSerif = Source_Serif_4({
  subsets: ["latin"],
  variable: "--font-heading",
  weight: ["400"],
});
const lusitana = Lusitana({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-secondary",
  display: "swap",
});

export const metadata: Metadata = {
  title: "social-medium",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${sourceSerif.variable} ${lusitana.variable} antialiased bg-light`}
      >
        {children}
      </body>
    </html>
  );
}
